### ISSUE TITLE
Empty page when using function

### ISSUE THREAD

**Issue by ben-github** [TomCafferty/plugin-function#3]
I installed the dokuwiki plugin functions on my Weatherwa install of dokuwiki. Install went fine, but when I try to use the plugin on a page, I get a blank page that doesn't have the "edit" "old revisions" sidebar. I have to manually add do=draft to the url to edit the page and remove the line:

<function=testanotherhelloWorld>

to get it back to normal. Using the preview window in draft mode shows a blank page too and gives me a heads up that the page isn't rendering. 

I'm using just the unedited template functions included with the plugin. If I try to use that with:

<function=anotherhelloWorld>

or a non-existent function with

<function=testanotherhelloWorld>

I get the same behavior.

Thanks,

Ben

**Comment by ben-github** [comment]
Github seems to have taken out the line of code that causes the problem. It is either

```
<function=badfilename>
```

or using one of the examples:

```
<function=anotherhelloWorld>
```

**Comment by TomCafferty** [comment]
Ben,
Thanks for pointing that out. The example.txt file was bad. I have updated the example.txt and the default file in the conf directory.  It should work now.  The bad example file was calling a file to execute that did not exists.  I see how that hangs the page up and you need to edit the file offline to correct.  I will look at how to handle an error like that better,  But for now the example.txt should work.
Best Regards
Tom
